<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/>
    </parent>

    <groupId>io.github.jocker-cn</groupId>
    <artifactId>java-impetus-dependencies</artifactId>
    <version>2.0.0</version>
    <name>java-impetus-dependencies</name>
    <description>Java Impetus framework All dependency</description>
    <packaging>pom</packaging>

    <properties>
        <java.version>21</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <maven.compiler.release>${java.version}</maven.compiler.release>
        <java-impetus.version>2.0.0</java-impetus.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <springdoc.version>3.1.1</springdoc.version>
        <lombok.version>1.18.48</lombok.version>
        <guava.version>33.7.2-jre</guava.version>
        <redisson.version>4.7.0</redisson.version>
        <apache-commons-collections4>4.6.0</apache-commons-collections4>
        <commons-lang3.version>3.21.0</commons-lang3.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <commons-codec.version>1.22.1</commons-codec.version>
        <google.zxing.version>3.5.4</google.zxing.version>
        <ezylang.version>3.7.0</ezylang.version>
        <jakarta.jakartaee-api.version>11.0.0</jakarta.jakartaee-api.version>
        <jakarta.el-api.version>6.0.1</jakarta.el-api.version>
        <expressly.version>6.0.0</expressly.version>
        <jackson-bom.version>3.2.3</jackson-bom.version>
        <jsr305.version>3.0.2</jsr305.version>
        <maven-gpg-plugin.version>3.2.8</maven-gpg-plugin.version>
        <maven-javadoc-plugin.version>3.12.0</maven-javadoc-plugin.version>
        <maven-source-plugin.version>3.4.0</maven-source-plugin.version>
        <nexus-staging-maven-plugin.version>1.7.0</nexus-staging-maven-plugin.version>
        <bcprov-jdk18on.version>1.86</bcprov-jdk18on.version>
        <commons-compress.version>1.28.0</commons-compress.version>
    </properties>

    <url>https://github.com/catch-money/java-impetus</url>

    <developers>
        <developer>
            <id>java-impetus</id>
            <name>jockerCN</name>
            <email>zh13825080826@gmail.com</email>
            <roles>
                <role>Developer</role>
            </roles>
            <timezone>+8</timezone>
        </developer>
    </developers>

    <licenses>
        <license>
            <name>Apache License</name>
            <url>https://www.apache.org/licenses/</url>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:https://github.com/catch-money/java-impetus.git</connection>
        <url>https://github.com/catch-money/java-impetus</url>
        <developerConnection>scm:git:ssh:https://github.com/catch-money/java-impetus/main</developerConnection>
    </scm>

    <dependencyManagement>
        <dependencies>

            <dependency>
                <groupId>tools.jackson</groupId>
                <artifactId>jackson-bom</artifactId>
                <version>${jackson-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>io.github.jocker-cn</groupId>
                <artifactId>java-impetus-common</artifactId>
                <version>${java-impetus.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.jocker-cn</groupId>
                <artifactId>java-impetus-toolkit</artifactId>
                <version>${java-impetus.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.jocker-cn</groupId>
                <artifactId>java-impetus-crypto</artifactId>
                <version>${java-impetus.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.jocker-cn</groupId>
                <artifactId>java-impetus-web-common</artifactId>
                <version>${java-impetus.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.jocker-cn</groupId>
                <artifactId>java-impetus-web-page</artifactId>
                <version>${java-impetus.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.jocker-cn</groupId>
                <artifactId>java-impetus-spring-common</artifactId>
                <version>${java-impetus.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.jocker-cn</groupId>
                <artifactId>java-impetus-jackson</artifactId>
                <version>${java-impetus.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.jocker-cn</groupId>
                <artifactId>java-impetus-redis</artifactId>
                <version>${java-impetus.version}</version>
            </dependency>


            <dependency>
                <groupId>io.github.jocker-cn</groupId>
                <artifactId>java-impetus-jpa</artifactId>
                <version>${java-impetus.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.jocker-cn</groupId>
                <artifactId>java-impetus-auth</artifactId>
                <version>${java-impetus.version}</version>
            </dependency>


            <dependency>
                <groupId>io.github.jocker-cn</groupId>
                <artifactId>java-impetus-auth-impl</artifactId>
                <version>${java-impetus.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-compress</artifactId>
                <version>${commons-compress.version}</version>
            </dependency>

            <dependency>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcprov-jdk18on</artifactId>
                <version>${bcprov-jdk18on.version}</version>
            </dependency>

            <dependency>
                <groupId>com.google.code.findbugs</groupId>
                <artifactId>jsr305</artifactId>
                <version>${jsr305.version}</version>
            </dependency>

            <!--  spring doc - swagger-ui -->
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc.version}</version>
            </dependency>
            <!--lombok-->
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
            <!-- guava           -->
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>
            <!-- redisson           -->
            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson</artifactId>
                <version>${redisson.version}</version>
            </dependency>
            <!-- commons-collections4           -->
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-collections4</artifactId>
                <version>${apache-commons-collections4}</version>
            </dependency>
            <!--  commons-lang3-->
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${commons-lang3.version}</version>
            </dependency>
            <!--  mapstruct-->
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <!--     jakartaee-api -->
            <dependency>
                <groupId>jakarta.platform</groupId>
                <artifactId>jakarta.jakartaee-api</artifactId>
                <version>${jakarta.jakartaee-api.version}</version>
                <scope>provided</scope>
            </dependency>
            <!--  commons-codec-->
            <dependency>
                <groupId>commons-codec</groupId>
                <artifactId>commons-codec</artifactId>
                <version>${commons-codec.version}</version>
            </dependency>
            <!-- google.zxing -->
            <dependency>
                <groupId>com.google.zxing</groupId>
                <artifactId>core</artifactId>
                <version>${google.zxing.version}</version>
            </dependency>

            <dependency>
                <groupId>jakarta.el</groupId>
                <artifactId>jakarta.el-api</artifactId>
                <version>${jakarta.el-api.version}</version>
            </dependency>

            <dependency>
                <groupId>org.glassfish.expressly</groupId>
                <artifactId>expressly</artifactId>
                <version>${expressly.version}</version>
            </dependency>

            <dependency>
                <groupId>com.ezylang</groupId>
                <artifactId>EvalEx</artifactId>
                <version>${ezylang.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>


    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>${maven-jar-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.sonatype.central</groupId>
                    <artifactId>central-publishing-maven-plugin</artifactId>
                    <version>0.11.0</version>
                    <extensions>true</extensions>
                    <configuration>
                        <publishingServerId>sonatype</publishingServerId>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-gpg-plugin</artifactId>
                    <version>${maven-gpg-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>sign-artifacts</id>
                            <phase>verify</phase>
                            <goals>
                                <goal>sign</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>${maven-javadoc-plugin.version}</version>
                    <configuration>
                        <additionalJOptions>
                            <additionalJOption>-Xdoclint:none</additionalJOption>
                        </additionalJOptions>
                    </configuration>
                    <executions>
                        <execution>
                            <id>attach-javadocs</id>
                            <goals>
                                <goal>jar</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>${maven-source-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>attach-sources</id>
                            <goals>
                                <goal>jar-no-fork</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>


    <profiles>
        <profile>
            <id>release</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>0.11.0</version>
                        <extensions>true</extensions>
                        <configuration>
                            <publishingServerId>sonatype</publishingServerId>
                            <autoPublish>true</autoPublish>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>${maven-gpg-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <version>${maven-javadoc-plugin.version}</version>
                        <configuration>
                            <additionalJOptions>
                                <additionalJOption>-Xdoclint:none</additionalJOption>
                            </additionalJOptions>
                        </configuration>
                        <executions>
                            <execution>
                                <id>attach-javadocs</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <version>${maven-source-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>attach-sources</id>
                                <goals>
                                    <goal>jar-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
